mutation CreatePost($content: String!) {
  createPost(createPostDto: { content: $content }) {
    id
    content
    userId
    user {
      id
      email
      nickname
      selfIntroduction
      createdAt
      updatedAt
    }
    createdAt
    updatedAt
  }
}

mutation EditPost($postId: String!, $content: String!) {
  editPost(editPostDto: { postId: $postId, content: $content }) {
    id
    content
    userId
    user {
      id
      email
      nickname
      selfIntroduction
      createdAt
      updatedAt
    }
    createdAt
    updatedAt
  }
}

mutation DeletePost($postId: String!) {
  deletePost(deletePostDto: { postId: $postId }) {
    id
    content
    userId
    user {
      id
      email
      nickname
      selfIntroduction
      createdAt
      updatedAt
    }
    createdAt
    updatedAt
  }
}
