query GetPosts {
  posts {
    id
    content
    userId
    user {
      id
      email
      nickname
      selfIntroduction
      createdAt
      updatedAt
    }
    createdAt
    updatedAt
  }
}

query GetPost($postId: String!) {
  post(getPostByIdDto: { postId: $postId }) {
    id
    content
    userId
    user {
      id
      email
      nickname
      selfIntroduction
      createdAt
      updatedAt
    }
    createdAt
    updatedAt
  }
}
